from django.db import models

# Create your models here.
# Models are tables in your database

class Book(models.Model):
    # The ID is automatically generated by Django
    name = models.CharField(max_length=50, default='')
    authors = models.JSONField(default=list, blank=True)
    publisher = models.CharField(max_length=50, default='', blank=True)
    language = models.CharField(max_length=50, default='', blank=True)
    pages = models.IntegerField(default=0)
    publication_date = models.DateField()
    isbn13 = models.CharField(max_length=14, default='', blank=True)
    genres = models.JSONField(default=list, blank=True)

    # Customize the get on the object
    def __str__(self):
        return f'Book: {self.name} from {self.authors}'