# Generated by Django 5.2.4 on 2025-07-08 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('authors', models.JSONField(blank=True, default=list)),
                ('publisher', models.CharField(blank=True, default='', max_length=50)),
                ('language', models.CharField(blank=True, default='', max_length=50)),
                ('pages', models.IntegerField(default=0)),
                ('publication_date', models.DateField()),
                ('isbn13', models.CharField(blank=True, default='', max_length=14)),
                ('genres', models.JSONField(blank=True, default=list)),
            ],
        ),
    ]
