# Generated by Django 5.2.4 on 2025-07-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0002_remove_book_id_alter_book_publisher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, default='', max_length=14, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
