# Generated by Django 5.2.4 on 2025-07-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_api', '0003_alter_book_isbn13_alter_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn13',
            field=models.CharField(blank=True, default='', max_length=14),
        ),
    ]
